//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot_AirPlaneType
    {
        public int Id { get; set; }
        public int AirplaneTypesId { get; set; }
        public int PilotId { get; set; }
    
        public virtual AirplaneType AirplaneTypes { get; set; }
        public virtual Pilot Pilot { get; set; }
    }
}
