//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportSystem.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Schedule
    {
        public int FlightNumber { get; set; }
        public int FromAirportId { get; set; }
        public int ToAirportId { get; set; }
        public string AirplaneRegNumber { get; set; }
        public int PilotId { get; set; }
        public Nullable<int> PilotIdCo { get; set; }

		[DisplayFormat (DataFormatString ="{0:yy-MM-dd}")]
        public System.DateTime ETA { get; set; }
		[DisplayFormat (DataFormatString ="{0:yy-MM-dd}")]
        public System.DateTime ETD { get; set; }
    
        public virtual Airport From { get; set; }
        public virtual Airport To { get; set; }
        public virtual Airplane Airplane { get; set; }
        public virtual Pilot PilotSet { get; set; }
        public virtual Pilot PilotSet1 { get; set; }
    }
}
